### ISSUE TITLE
visibilitychange event doesn't return document in 'this'

### ISSUE THREAD

**Issue by morenoh149** [oliviertassinari/react-event-listener#1]
Nice module.
I'm trying the following
```javascript
import React from 'react'
import Router from 'react-router'
import { Route, DefaultRoute, RouteHandler } from 'react-router'
import LocalStorageMixin from 'react-localstorage'
import EventListener from 'react-event-listener'

/*
 * Top level Component
 */
let App = React.createClass({
  mixins: [
    EventListener,
    LocalStorageMixin
  ],
  listeners: {
    document: {
      visibilitychange: 'onVisibilityChange'
    }
  },
  onVisibilityChange: function() {
    // the variable this refers to the document object
    console.log('visbility state:', this)
  },
  render() {
    return (
      <RouteHandler />
    )
  }
})
```
the this object looks like
![screenshot 2015-07-28 16 44 35](https://cloud.githubusercontent.com/assets/587438/8946750/f5bc8514-3547-11e5-83a7-84bedde32ece.png)
I was expecting it to return the `document` object. Which would have [document.hidden](https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API)

**Comment by oliviertassinari** [comment]
Ok, looks like my documentation is wrong. May be the react autobinding that is responsible of this see https://facebook.github.io/react/blog/2013/07/02/react-v0-4-autobind-by-default.html. Let me investigate.

**Comment by oliviertassinari** [comment]
So yes.
You can directly use `document` instead.
I have updated the document. Thanks for reporting this issue :+1:.
