### ISSUE TITLE
React as peer dependency

### ISSUE THREAD

**Issue by danielstreit** [oliviertassinari/react-event-listener#14]
Thanks for the project, this is a great idea!

Should react be added as a peer dependency to the package.json?

**Comment by oliviertassinari** [comment]
Yeap, we could. We mostly depend on the React hooks.
I believe we support a wide range of React versions

**Comment by danielstreit** [comment]
Yeah, looks like the component itself should work on any version of React.

The react-addons-shallow-compare has a peer dependency on react being the same version or higher than the addon package itself. 

So...maybe it doesn't make sense to add a specific React peer dependency because it is included by the addon?

**Comment by oliviertassinari** [comment]
> So...maybe it doesn't make sense to add a specific React peer dependency because it is included by the addon?

I would rather be explicit with a `devDependency`. Do you want to submit a PR?

**Comment by danielstreit** [comment]
I looked into this a little more, and I think npm handles unresolved peerDependencies of dependencies pretty well. There should be no need to add react as a peerDependency here. Closing.
