### ISSUE TITLE
using window[target]

### ISSUE THREAD

**Issue by EliranShemesh** [oliviertassinari/react-event-listener#18]
First of all - great component! 
Two question though: 
is using window[target] not considered antipattern? is this not targeting the DOM itself, instead of the shadow dom, thus breaking the react tree/chain? 
Also - is there a way to make the target element a specific react component, instead of a dom element?

**Comment by oliviertassinari** [comment]
> is there a way to make the target element a specific react component, instead of a dom element?

What would be your use case?

> is using window[target] not considered antipattern?

It's the whole point of this lib. Proving a helper to listen for global events.

> instead of the shadow dom, thus breaking the react tree/chain?

How is this breaking the react tree/chain?

**Comment by EliranShemesh** [comment]
> How is this breaking the react tree/chain?

React is always comparing its shadow dom to the existing dom, and when there is a difference it updates the specific elements of the page. When you directly target a dom element, does not have this element's shadow dom copy anymore, and thus the break. Did I got it wrong? I read in several places that targeting dom elements is not the way to use react. Maybe I misunderstood?

**Comment by oliviertassinari** [comment]
> I read in several places that targeting dom elements is not the way to use react.

It depends on the use case. What's your use case?
If you want to listen to low-level dom element rendered by React, using the synthetic event system of React would indeed be much better.
But with nodes rendered outside of the React three, top-level nodes in our case, you need a bridge.

**Comment by EliranShemesh** [comment]
>  What's your use case?
Well, I've got to render html from a string I get from an outside source, so I use dangerouslySetInnerHTML (trusted source). When the component mount, I want to listen to clicks from links within this html, than catch and push them to react router, so the page won't refresh.
` handleClick(event) {
+    const { href } = event.target.attributes;
+
+    if (href && href.nodeValue) {
+      if (href.nodeValue.includes('http://')) {
+        window.location.href = href.nodeValue;
+        return;
+      }
+
+      event.preventDefault();
+      browserHistory.push(href.nodeValue);
+    }
+  }
+
+  render() {
+    return (
+      <div>
+        {
+          this.state.didMount
+            ? <EventListener
+              target={ this.refs.outerHtml }
+              onClick={ this.handleClick } />
+            : ''
+        }
+        <div
+          ref="outerHtml"
+          dangerouslySetInnerHTML={
+            { __html: this.props.html }
+          } />
+      </div>
+    );
+  }`

**Comment by oliviertassinari** [comment]
I haven't tested it, but I would expect:
```jsx
        <div
          ref="outerHtml"
          dangerouslySetInnerHTML={
            { __html: this.props.html }
          }
      onClick
      />
```

**Comment by EliranShemesh** [comment]
I have. And it works. For some reason I was sure using onClick won't work on this. Thank you! It seems like I need to learn more about events handling in general :)

**Comment by oliviertassinari** [comment]
Awesome, let's close this issue :).
