### ISSUE TITLE
How does one unit test this component inside our own?

### ISSUE THREAD

**Issue by rfgamaral** [oliviertassinari/react-event-listener#25]
For instance, take the following TypeScript example:

```ts
export default class MyComponent extends React.Component<any, any> {

    constructor() {
        super();

        this.handleDocumentKeyDown = this.handleDocumentKeyDown.bind(this);
    }

    public render(): JSX.Element {
        return (
            <div>
                <FooComponent />
                <EventListener
                    target="document"
                    onKeyDown={this.handleDocumentKeyDown} />
                <BarComponent />
            </div>
        );
    }

    private handleDocumentKeyDown(event: any): void {
        if (event.keyCode === KeyCodes.Enter) {
            // do something...
        }
    }

}
```

How do I render `MyComponent`, create and set a spy function on `onKeyDown` property of `EventListener` and simulate that event (with proper key code as parameter) so that I can assert that the spy was called with the expected key code?

I am using Jest (`jest.fn()` to create spies) and Enzyme (shallow render) on my test suite but if you give me an example with other framework/tools, maybe I can convert it to my own. I just need a push in the right direction...

I've already tried something like the following:

```ts
const spy = jest.fn();
const myComponent = shallow(<MyComponent />);
const eventListener = myComponent.find(EventListener).dive();

eventListener.setProps({
    onKeyDown: spy,
});

eventListener.simulate("onKeyDown");

expect(spy).toHaveBeenCalled();
```

But it was never called... Not sure what I'm doing wrong :(

**Comment by oliviertassinari** [comment]
It depend on how deep you want to test the stack.
It seems that you only want to use the *shallow rendering* API.
Have you tried the following?
```jsx
eventListener.simulate("keyDown");
```
that should be equivalent to:
```jsx
eventListener.props.onKeyDown();
```

You can also have a look at the [unit test suite of the lib](https://github.com/oliviertassinari/react-event-listener/blob/master/src/index.spec.js).

**Comment by rfgamaral** [comment]
Tried this right now:

```ts
const spy = jest.fn();

const eventListener = shallow(
    <EventListener
        target="document"
        onKeyDown={spy} />
);

eventListener.simulate("keyDown");

expect(spy).toHaveBeenCalled();
```

Got this:

```
expect(jest.fn()).toHaveBeenCalled()

Expected mock function to have been called.

× encountered a declaration exception

Not sure what's going on...
```

**Comment by rfgamaral** [comment]
Did a couple more tests...

**`#1)`**

```ts
const component = shallow(<MyComponent />);
const eventListener = component.find(EventListener);

eventListener.simulate("keyDown")({
    keyCode: 123
});
```

This one gave me this:

> TypeError: Cannot read property 'keyCode' of undefined

**`#2)`**

```ts
const component = shallow(<MyComponent />);
const eventListener = component.find(EventListener);

eventListener.props().onKeyDown({
    keyCode: 23
});
```

This one worked. Shouldn't both have worked?

This is slightly different from my original question where I was using a spy to assert if the handler was being called but I don't really need to check for that. I need to test my code and my code does something when certain keys are pressed.

Given that, I can use the second working example (which is very similar to what you said) to simulate a specific `keyDown` event. Then assert that my code does what I expect it to do when that certain event was fired. I think this makes more sense, doesn't it?

**Comment by oliviertassinari** [comment]
> Shouldn't both have worked?

I don't think so. I haven't tested, but I'm expecting the following to work:
```js
const wrapper = shallow(<MyComponent />);
const eventListener = wrapper.find(EventListener);

eventListener.props().onKeyDown({
    keyCode: 23, 
});

eventListener.simulate('keyDown', {
    keyCode: 23, 
});
```

That issue sounds like a question regarding the usage of the enzyme API. That's not specific to this component. I'm closing it.

**Comment by rfgamaral** [comment]
Yeah, that `simulate` version worked nicely. I was confused by something else, my bad. Sorry for this and thank you for your help, really appreciated :)
