### ISSUE TITLE
Use default target if none specified

### ISSUE THREAD

**Issue by dlindenkreuz** [oliviertassinari/react-event-listener#29]
Currently, the component [does not do anything](https://github.com/oliviertassinari/react-event-listener/blob/master/src/index.js#L148) if no `target` prop was specified.

It probably should use `window` or at least warn about a missing target.

**Comment by oliviertassinari** [comment]
I think that we should make the target required. This package used to be a mixin, we hadn't the option at that time

Providing a default value sounds like a bad idea, some events can only be listened on the `document` and `window` respectively.
