### ISSUE TITLE
Thoughts on a setTimeout property

### ISSUE THREAD

**Issue by Cottin** [oliviertassinari/react-event-listener#3]
First, thanks a lot for this declarative event listener approach! It's very nice :)

I found my self needing a global onClick event to listen for when to call a `onRequestClose` callback to close a Popover component but the listener get there too early and calling `onRequestClose` on the same click that opened it.

So... I added a quick implementation for `setTimeout` below that successfully solved my problem. What you think of this new prop, is it viable or am I miss-using the react-event-listener concept?

```
export default class EventListener extends React.Component {
	static propTypes = {
        ...
		setTimeout: React.PropTypes.number,
	}

	constructor(props) {
		super(props)
	}

	componentDidMount() {
		if (this.props.setTimeout) {
			setTimeout(() => {
				listenersForEach(this.props, (element, eventName, callback) => {
					on(element, eventName, callback)
				})
			}, this.props.setTimeout)
		} else {
			listenersForEach(this.props, (element, eventName, callback) => {
				on(element, eventName, callback)
			})
		}
```

**Comment by jedwards1211** [comment]
This would be scope creep for this library.  You can just call `setTimeout` yourself in the listener you pass to `EventListener`:
```jsx
const delay = 17;
const onDocumentClick = () => setTimeout(onRequestClose, delay);
...
<EventListener elementName="document" onClick={onDocumentClick} />
```

**Comment by oliviertassinari** [comment]
I agree with @jedwards1211I would rather keep the implementation simple and not introduce a `timeout` nor a `debounce` nor a `throttle` property.
However, we could provide an HOC for this behavior 👍.

**Comment by Cottin** [comment]
`setTimeout` in a `onDocumentClick` would not work in my case. Note that I'm not trying to offset the firing of a callback after a click is made but instead I'm interested in offsetting the **subscription** of the listeners.

If I did what you're suggesting in the snippet, the popover will still be closed on the same click that opened it, it will just close 17 milis later :)

**Comment by jedwards1211** [comment]
@Cottin in that case, you should only render the `<EventListener>` when the popover is open.  The idea behind a declarative listening API like this is that you declare the listeners only at the time they should be attached.

**Comment by Cottin** [comment]
That's what I am doing:

```
	render() {
		if (!this.props.isOpen) return null

		return div({style: {display: 'none'}},
			EventListener({
				elementName: 'window',
				setTimeout: 0,
				onClick: this.onClick,
				onTouchStart: this.onClick,
				onResize: throttle(this.setPlacement, 10),
				onScroll: throttle(this.setPlacement, 10),
			}),
			Portal({
				ref: 'layer',
				render: this.renderLayer,
			})
		)
	},
```

`EventListener` only rendered when `isOpen` is true. However when `isOpen` gets set to true, without the setTimeout, the listeners gets registered so fast that they pick ut the same click-event that actually set the `isOpen` prop to true (that onClick callback is in the parent of the Popover component).

**Comment by jedwards1211** [comment]
Wow.  In that case, why not just use `setTimeout` to delay rendering with `isOpen: true`?

**Comment by Cottin** [comment]
Good idea :)

So, I tried it and if I only use `setTimeout` in the onClick-callback of the parent like so:
```
open() {
  setTimeout((() => this.setState({isOpen: true}), 0)
}
```
...it works fine when clicking the button to open it.

However when you click the button again, it closes the popover, but then directly, it opens it up again.
Probably because the onClick gets fired, which both triggers the `onRequestClose` callback and it also triggers the `open` callback since the onRequestClose sets the state immediately to false, it gets closed but then 0 millis later (= last in the execution queue) setState setting it to true again is triggered and the popover is re-opened.

So... should we also use setTimeout for `close` (which `onRequestClose` is calling)?
```
close() {
  setTimeout((() => this.setState({isOpen: false}), 0)
}
```
...yes, then it seems to work as expected, clicking the button for the second time will close the popover.

However, if we make it a bit more complicated, let's say we have multiple buttons and multiple popovers like so:

```
getInitialState() {
  return { openPopoverId: null }
}
...
Button({onClick: this.open('A')}, 'Open A')
Popover({isOpen: this.state.openPopoverId === 'A'}, 'Popover A')
Button({onClick: this.open('B')}, 'Open B')
Popover({isOpen: this.state.openPopoverId === 'B'}, 'Popover B')
```

...and we're using the same `setTimeout` concept in both `open(id)` and `close` in the parent, we get a problem when first clicking Button A and then clicking Button B. The problem is that 'Popover A' is opened and when you click Button B you'd like Popover A to close and Popover B to open. Whats happening though, is that Popover A closes and Popover B opens and just after Popover B closes again.

With the `setTimeout` prop on `EventListener` this worked as expected.

Also, I apologize for spamming you guys here! If you feel like you don't want to spend too much time helping me out in this specific use case, I'd happily accept the "scope creep" argument and do a fork and add my `setTimeout` prop myself.  I can't seem to find another way of doing this :)

**Comment by jedwards1211** [comment]
@Cottin actually, it will probably be more foolproof if you look at the target in your `onClick` handler, and ignore the event if the user clicked on a descendant of the popover or the button that triggered it.

**Comment by Cottin** [comment]
@jedwards1211 yes, thanks, I thought about that. I just like the simplicity of the setTimeout prop. Thanks anyway :)

**Comment by oliviertassinari** [comment]
> it will probably be more foolproof if you look at the target in your onClick handler, and ignore the event if the user clicked on a descendant of the popover or the button that triggered it.

@Cottin You could be using [ClickAwayListener](https://github.com/callemall/material-ui/blob/master/src/internal/ClickAwayListener.js) for this.
