### ISSUE TITLE
Target component

### ISSUE THREAD

**Issue by OliverJAsh** [oliviertassinari/react-event-listener#44]
Hi there, thanks for the great library!

I want to attach a `transitionend` event to my component, but I want to avoid using React's synthetic event system because I need to know the specific time the real browser event occurred. For context, this is so I can measure the time between events with the User Timing API.

I have something like this:

``` jsx
      <EventListener
        target={this.transitionEl}
        onTransitionEnd={this.onTransitionEnd.bind(this)}
      >
        <div
          ref={(ref) => { this.transitionEl = ref; }}
        >
// …
```

This works, but I get a warning because, on the initial render, `this.transitionEl` is `undefined` (the `ref` hasn't been set yet).

Is this safe to do? Do you have any better recommendations?

Thanks!

**Comment by oliviertassinari** [comment]
> I want to avoid using React's synthetic event system 

Hey, thanks for raising that concern, that's an interesting use case!

> This works, but I get a warning 

The warning has been introduced with #31, we could revert.

I have been using a [different solution](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views/src/SwipeableViews.js#L426) on react-swipeable-view as we do with Material-UI.
I'm not sure what's the best answer is.

**Comment by oliviertassinari** [comment]
> Is this safe to do?

Yes, it's. 

> Do you have any better recommendations?

You miss the event prefixes with that solution. I discovered it with https://github.com/react-bootstrap/dom-helpers/pull/19.
So I would recommend using an event prefixing tool.

Regarding improving the API for that use case. I have thought about adding a `targetSetter` property, that could be used like this:
```js
<EventListener
  targetSetter={(setter) => this.targetSetter = setter}
  onTransitionEnd={this.onTransitionEnd.bind(this)}
>
  <div
    ref={(ref) => { this.targetSetter(ref) }}
  >
// ...
```
I'm not sure it's a good idea. What do you think?
