### ISSUE TITLE
Keypress doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by Fralleee** [oliviertassinari/react-event-listener#58]
Can't seem to make it work in Edge-browser.

`<EventListener target='window' onKeyPress={this.handleDocumentClick} />`

```
handleDocumentClick(e) {
  console.log(e) 
}
```

Works fine in Chrome & FF

**Comment by oliviertassinari** [comment]
The following code is working on my end with Edge 15. What version are you using? I'm not sure what's going on.
```js
window.addEventListener('keypress', console.log)
```

**Comment by Fralleee** [comment]
Microsoft EdgeHTML 15.15063

Yes addEventListener works fine if I call it manually in my code or console but the EventListener-component doesn't seem to work for me.

**Comment by oliviertassinari** [comment]
I have no idea what could go wrong here. Sounds really weird! Did you get any other even type working? Let us know if you find a solution.
