### ISSUE TITLE
Error with Flow 54

### ISSUE THREAD

**Issue by andreawyss** [oliviertassinari/react-event-listener#61]
Error: node_modules/react-event-listener/src/index.js:49
 49:   children?: React.Element<any>,
                  ^^^^^^^^^^^^^^^^^^ Element. Property not found in
                              v-
234:   declare export default {|
235:     +DOM: typeof DOM,
236:     +PropTypes: typeof PropTypes,
...:
248:   |};
       -^ object type. See lib: /private/tmp/flow/flowlib_5981b62/react.js:234

Error: node_modules/react-event-listener/src/index.js:102
102: class EventListener extends Component {
                                 ^^^^^^^^^ identifier `Component`. Too few type arguments. Expected at least 1
 29: declare class React$Component<Props, State = void> {
                                   ^^^^^^^^^^^^ See type parameters of definition here. See lib: /private/tmp/flow/flowlib_5981b62/react.js:29

**Comment by oliviertassinari** [comment]
> children?: React.Element,

We don't have such occurrence on the source code. Please make sure you are using the latest version of the lib.

**Comment by oliviertassinari** [comment]
https://github.com/oliviertassinari/react-event-listener/blob/4a1a7e904940ad952b3b3ad9d3657cb365bc2b10/src/index.js#L50

**Comment by andreawyss** [comment]
Adding this to .flowconfig fixed the issue:
[ignore]
.*/node_modules/react-event-listener/src/.*

**Comment by nwaywood** [comment]
I was also getting the same error, @andreawyss solution didn't work for me. I had to add

```
[ignore]
.*/node_modules/react-event-listener/src/.*
```
