### ISSUE TITLE
React 16.0 support.

### ISSUE THREAD

**Issue by bytor99999** [oliviertassinari/react-event-listener#62]
Not sure if it would require more work than just changing the one line in the package file.

**Comment by oliviertassinari** [comment]
It's already supported by we can remove the beta from the path :+1:
```jsx
  "peerDependencies": {
    "react": "^15.3.0 || ^16.0.0-beta.5"
  }
```

**Comment by bytor99999** [comment]
Thank you very much for this and all the work you do on these projects. Very much appreciated.

Mark
