### ISSUE TITLE
Module not found: Can't resolve '@babel/runtime/helpers/builtin/es6/getPrototypeOf'

### ISSUE THREAD

**Issue by kirill-konshin** [oliviertassinari/react-event-listener#77]
Seems that something is broken in latest release. I had to roll back to `0.5.3`.

./node_modules/react-event-listener/dist/react-event-listener.esm.js
Module not found: Can't resolve '@babel/runtime/helpers/builtin/es6/getPrototypeOf' in '/xxx/node_modules/react-event-listener/dist'

**Comment by oliviertassinari** [comment]
0.5.5 should be working too.

**Comment by oliviertassinari** [comment]
- https://unpkg.com/@babel/runtime@7.0.0-beta.47/helpers/builtin/es6/getPrototypeOf.js (ok)
- https://unpkg.com/@babel/runtime@7.0.0-beta.42/helpers/builtin/es6/getPrototypeOf.js (ko)

**Comment by oliviertassinari** [comment]
Can you try v0.5.7?

**Comment by oliviertassinari** [comment]
Alright, we should be back on track https://bundlephobia.com/result?p=react-event-listener@0.5.7. I wasn't expecting a babel runtime mismatch that soon. Let's hope it will continue to work like this for the next babel-runtime releases.

**Comment by oliviertassinari** [comment]
0.6.0 is out.

**Comment by Johnstands** [comment]
I'm getting the same problem.

`"name": "react-event-listener",
  "version": "0.6.3"`
