### ISSUE TITLE
IE10 - TypeError: "Cannot call a class as a function"

### ISSUE THREAD

**Issue by nwessing** [oliviertassinari/react-event-listener#80]
When rendering this component in IE10, I get a TypeError exception with a message of "Cannot call a class as a function". I get this error using version 0.5.9, but everything seems to work fine using version 0.5.3. I have not tested the versions in between.

It seems that this there is a bug in the transpilation with causes the prototype to not be wired up correctly for IE10.

The error is thrown in react-dom. react-dom wants the following property to be defined in order to use the component as a constructor.

`EventListenter.prototype.isReactComponent`

In IE10 this expression is undefined. One thing I did notice is that this expression IS defined:

`EventListener.prototype.__proto__.isReactComponent`

react-dom attempts to render this as a functional component instead of a class component, which is what causes the exception to be thrown.

**Comment by oliviertassinari** [comment]
@nwessing IE support starts at IE11. It's a direct dependency of Material-UI. We support the same versions.
