### ISSUE TITLE
Possibly unnecessary @babel/runtime?

### ISSUE THREAD

**Issue by DreadBoy** [oliviertassinari/react-event-listener#85]
I noticed Webpack bundles @babel/runtime and I traced it back to this module. Is it necessary to include it in prod build? I'd like to reduce build size and react-event-listener is 1.82kb while @babel/runtime is 2.3kb.

**Comment by TrySound** [comment]
@DreadBoy Yes, it's necessary. Babel always adds helpers. Babel runtime allows to deduplicate them across many packages. However we can disable polyfilling which is usually produces es3 compatible code. By the way polifills will be disabled by default in the future versions.

**Comment by oliviertassinari** [comment]
@DreadBoy We have already been working on reducing the bundle size: https://bundlephobia.com/result?p=react-event-listener@0.6.1. 
`@babel/runtime` is simply a wrapper to `core-js`. core-js is a dependency you are going to share with a lot of other dependencies. I fear we can't do more.

**Comment by TrySound** [comment]
@oliviertassinari FYI babel runtime with builtins enabled doesn't use core-js at all. This makes it possible to provide pure esm output.
