### ISSUE TITLE
【Important】not work with babel-runtime@beta.56 

### ISSUE THREAD

**Issue by monkindey** [oliviertassinari/react-event-listener#86]
The babel-runtime@beta.56 [split @babel/runtime into two separate runtime modules](https://github.com/babel/babel/commit/a8224d40e2ff5d2ef92152e4853257596d8097bc).

and the react-event-listener will resolve the `@babel/runtime/helpers/builtin/typeof` and other helpers, but they were removed to another package, so it will throw not found error.

 
![image](https://user-images.githubusercontent.com/6913898/43672284-5bd11a86-97dd-11e8-93ff-c526ef3cb505.png)

**Comment by InvictusMB** [comment]
@matthoffner Could you also release this as a hotfix for v0.5?
I have a transitive dependency through another package on react-event-listener@^0.5.x which now breaks the build

**Comment by oliviertassinari** [comment]
@InvictusMB I'm sorry, I won't.

**Comment by oliviertassinari** [comment]
What's the transitive dependency?

**Comment by InvictusMB** [comment]
@oliviertassinari 
It is `material-ui` beta which is in turn pinned because `material-ui` RC dropped support for older Reacts.

**Comment by oliviertassinari** [comment]
@InvictusMB 0.6.3 supports React 15.x too, you will only have a peer dependency warning.
