### ISSUE TITLE
Fix @babel/runtime version on v5

### ISSUE THREAD

**Issue by scastiel** [oliviertassinari/react-event-listener#88]
Hi! We use a package that depends on *react-event-listener* in version 5.x. Since Babel broke something in their last beta (beta 56) we have an error. I see you fixed it in the version 6.2 but as we use version 5 we don’t have the fix :(

Would it be possible to create a new version 5.10 that integrates the fix, i.e. fixes @babel/runtime version to 7.0.0-beta.42?

I could actually create a PR, but for that I would need a branch v5… ;)

Thanks!

**Comment by oliviertassinari** [comment]
@scastiel As far as I know, 6.2 works with React 15.3.x too. The only issue is going to be the peer dependency warning. Is this something you can live with before upgrading to React 16?

**Comment by scrambled2k3** [comment]
I am seeing this as well.  I am on React v16 and using Material-UI prior to the 1.0 release (which requires react-event-listener "^0.5.1").  A 5.10 release with a fix for this would be great because currently that babel breaking change is completely causing our builds to fail.

**Comment by oliviertassinari** [comment]
Alright, I'm gonna make a release to fix the problem this evening.

**Comment by scastiel** [comment]
Great, thanks a lot!

**Comment by jack-bischoff** [comment]
This would be a _huge_ help for me and my team. Thanks!

**Comment by oliviertassinari** [comment]
0.5.10 is out.

**Comment by arturfsousa** [comment]
@oliviertassinari thanks a lot man
