### ISSUE TITLE
Handling events in capture phase

### ISSUE THREAD

**Issue by jaroslav-kubicek** [oliviertassinari/react-event-listener#9]
Thanks for this component!

I was thinking about the way how events are handled in capture phase - React use onEventXXXCapture, so have you considered this approach? Is it worth to create pull request or is there design decision behind having special `capture` prop?

**Comment by oliviertassinari** [comment]
I haven't considered this approach at all. Could you explain in more details what you are referring to? I'm also curious about the benefit.
I was considering trying our the [PanResponder](https://github.com/necolas/react-native-web/blob/master/src/apis/PanResponder/index.js) for future versions.

**Comment by jaroslav-kubicek** [comment]
Basically, if I want to handle event in capture phase, I can write code like this: `<CustomComponent onClickCapture={this.onClick} />` and React will add the provided listener for capture phase. On the other hand, this component instead relies on separate `capture` property that is applied globally to all listeners that were provided to this component.

**Comment by oliviertassinari** [comment]
Thanks for the explanation. I didn't know about it. Now,
What's the advantage? How do you handle nested `SwipeableView` / *scroll* containers?
Shouldn't the leaf element handle the event first?

**Comment by oliviertassinari** [comment]
Thanks for the explanation. I didn't know about it: [events](https://github.com/facebook/react/blob/master/docs/docs/ref-05-events.md#supported-events).

What would be the advantage?
I don't think that the API should provide two ways to do the same thing. But that would allow to have a detail control between two handlers.

**Comment by oliviertassinari** [comment]
> Is it worth to create pull request

Yes, that sounds like a valuable contribution. Do you have a real word use case for it?
