### ISSUE TITLE
Incorrect link in CHANGELOG

### ISSUE THREAD

**Issue by Fandekasp** [oliviertassinari/react-event-listener#91]
the link in this repo's CHANGELOG points to https://github.com/oliviertassinari/react-swipeable-views/releases. Got me really confused, since I use both packages in my project (react-event-listener being a dependency by material-ui  which broke when I tried to upgrade to material-ui v1 (related to https://github.com/oliviertassinari/react-event-listener/issues/90))

**Comment by oliviertassinari** [comment]
@Fandekasp Thanks for raising the issue.
